### ISSUE TITLE
Minor Spelling Mistake

### ISSUE THREAD

**Issue by ghost** [34736384/genshin-fps-unlock#425] opened 2024-06-26 17:08 UTC
![image](https://github.com/34736384/genshin-fps-unlock/assets/84100659/aa08f807-93a3-4066-ac2a-487c49b96f47)

**Comment by BlueStarBRS** [comment] 2024-06-26 23:09
haha  lol

**Comment by 34736384** [comment] 2024-06-26 23:11
duplicate of #388

**Closed as not planned by 34736384** 2024-06-26 23:11 UTC
