### ISSUE TITLE
The new version always fails to apply the FPS unlock when opening Genshin for the first time after a fresh PC boot.

### ISSUE THREAD

**Issue by HwangSeolhan** [34736384/genshin-fps-unlock#156] opened 2023-05-27 02:57 UTC
This has been happening to me since I updated to the latest version. After a fresh PC boot, the very first time that I open Genshin with the fpsunlock always fails to apply the fps cap (afterburner displays that I only have 60 FPS). After closing the game and reopening it via fpsunlock, that is when it uses my designated FPS. I have the same configurations as when I have the previous version, which has never happened to me before.

![Launch Options](https://github.com/34736384/genshin-fps-unlock/assets/90767085/54966a60-5ac8-4e89-b5dc-03e4ec0aa1b8)
![Menu](https://github.com/34736384/genshin-fps-unlock/assets/90767085/588d210c-76c6-4792-89f0-b9bad02aaf15)
![General](https://github.com/34736384/genshin-fps-unlock/assets/90767085/afee42e1-c706-4882-8560-77ff29f3ac13)

**Comment by haotianluo420** [comment] 2023-05-27 10:49
same, but its not only fresh pc boot for me, sometimes it just doesn't work but if i just restart the program it works again

**Comment by Veriiix** [comment] 2023-05-27 11:03
Auto close is broken too

**Comment by BlueStarBRS** [comment] 2023-05-27 19:31
![Screenshot 2023-05-27 212927](https://github.com/34736384/genshin-fps-unlock/assets/25110093/4513d200-9f93-4529-af7c-80bf556886f6)
it seeems
![Screenshot 2023-05-27 212952](https://github.com/34736384/genshin-fps-unlock/assets/25110093/42690e65-412b-4eb0-98b2-3b3d86375c50)
 thats the reson why it dont change anything ...

**Comment by BlueStarBRS** [comment] 2023-05-27 19:35
@34736384 can you work pls on a fix for it ?

**Comment by 34736384** [comment] 2023-05-27 19:45
> @34736384 can you work pls on a fix for it ?

cannot reproduce, so my answer is no

**Comment by Arcanologue** [comment] 2023-05-27 20:02
> > @34736384 can you work pls on a fix for it ?
> 
> cannot reproduce, so my answer is no

We all seem o have the same  issue :
When This tool is lauching the game FOR THE FIST TIME (1 per restart) it never apply the selected FPS.

i've got 3 differents comptuers that behave the same way...

**Comment by 34736384** [comment] 2023-05-27 20:04
> > > @34736384 can you work pls on a fix for it ?
> > 
> > 
> > cannot reproduce, so my answer is no
> 
> We all seem to have the same issue : When This tool is lauching the game FOR THE FIST TIME (1 per restart) it never apply the selected FPS.
> 
> i've got 3 differents comptuers that behave the same way...

I've tested on 3 computers, they all worked fine. I cannot fix something that I cannot reproduce

**Comment by Veriiix** [comment] 2023-05-27 20:20
"DllList": [],
  "Priority": 3,
  "MonitorNum": 1,
  "CustomResY": 1080,
  "CustomResX": 1920,
  "FPSTarget": 144,
  "UsePowerSave": false,
  "StartMinimized": true,
  "IsExclusiveFullscreen": false,
  "UseCustomRes": false,
  "Fullscreen": false,
  "PopupWindow": true,
  "AutoClose": true,
  "AutoDisableVSync": true,
  "AutoStart": true,
  
  i am facing the issues using these settings

**Comment by Veriiix** [comment] 2023-05-27 20:55
I tried experimenting with the settings and restarted each time. The issues persists after every single reboot

**Comment by vraixen** [comment] 2023-05-28 07:28
same issue i have an shortcut on the desktop for the launcher

**Comment by MbaoWang** [comment] 2023-05-28 08:08
Try using old driver <530, it may fixed the problems.

**Comment by Veriiix** [comment] 2023-05-28 10:57
@MbaoWang problem happens on AMD too

**Comment by haotianluo420** [comment] 2023-05-28 11:18
> @MbaoWang problem happens on AMD too

Yeh i got amd and it's the same

**Comment by HwangSeolhan** [comment] 2023-05-28 11:35
Anyone found a workaround for this issue? It's really annoying :<

It seems like the bug happens no matter what configurations you have on your fpsunlock menu.

**Comment by truyentd** [comment] 2023-05-28 16:12
> @MbaoWang problem happens on AMD too
I also facing the same problem. It didn't work the first time. Then I quit genshin, opened it again and it worked

**Comment by BlueStarBRS** [comment] 2023-05-28 19:18
> > > > @34736384 can you work pls on a fix for it ?
> > > 
> > > 
> > > cannot reproduce, so my answer is no
> > 
> > 
> > We all seem to have the same issue : When This tool is lauching the game FOR THE FIST TIME (1 per restart) it never apply the selected FPS.
> > i've got 3 differents comptuers that behave the same way...
> 
> I've tested on 3 computers, they all worked fine. I cannot fix something that I cannot reproduce

well this is a bit disappointing...
as example my system is using win 10
![image](https://github.com/34736384/genshin-fps-unlock/assets/25110093/9a5342c7-fb95-4f58-a24b-649a8ddb757c)

**Comment by BlueStarBRS** [comment] 2023-05-28 20:01
@34736384 https://streamable.com/sgrcmh here a vid what show it perfectly

also try to maybe try another adress,pointer,offset maybe that would help
maybe you got one that only works on secound start of the game after boot

**Comment by Arcanologue** [comment] 2023-05-28 20:21
- [ ] Windows 11 Professionnel - 22H2
- [ ] AMD Ryzen 7 3700X 8-Core Processor 
- [ ] Nvidia RTX3080TI (Founders Ediiton)
- [ ] X570 AORUS ELITE

**Comment by sefinek24** [comment] 2023-05-29 01:34
> * [x]  Windows 11 Professionnel - 22H2
> * [x]  AMD Ryzen 7 3700X 8-Core Processor
> * [x]  Nvidia RTX3080TI (Founders Ediiton)
> * [x]  X570 AORUS ELITE

Windows 11 😥✋ bruhh
slow mode was successfully activated! tf

https://github.com/34736384/genshin-fps-unlock/assets/92880265/3d8e476c-69db-407c-83b1-1fd3dc7e292c

**Comment by WilliamLeGod** [comment] 2023-05-29 03:55
I thought I was crazy but here we are, so many people have this same issue. Not work everytime PC reboot, only works 2nd times after the first failed

Windows 11 3080ti latest driver as of now

Please help :(

**Comment by BlueStarBRS** [comment] 2023-05-29 18:20
@34736384  https://github.com/34736384/genshin-fps-unlock/issues/156#issuecomment-1565351947
i can also confirm that the programm dont auto exit after the first time closing the game when the dont apply bug problem appears

**Comment by 34736384** [comment] 2023-05-29 20:18
Try the latest release

**Comment by BlueStarBRS** [comment] 2023-05-29 22:30
> 

Confirmed it works again! 
in this video i tested first boot and auto close issue both are fixed -> https://streamable.com/u4905p

so... @34736384 what whas broken ?

**Comment by HwangSeolhan** [comment] 2023-05-30 04:08
> Try the latest release
@34736384 Thank you for fixing it! But in my case, there is an error that always pops up when I open the game after first boot. Despite having an error like this, the unlock fps now work as intended at first try so I am not sure what this error is implying.
![image](https://github.com/34736384/genshin-fps-unlock/assets/90767085/33153460-6d2c-467a-b750-37c7a8a4e864)

**Comment by 34736384** [comment] 2023-05-30 07:18
> > Try the latest release
> > @34736384 Thank you for fixing it! But in my case, there is an error that always pops up when I open the game after first boot. Despite having an error like this, the unlock fps now work as intended at first try so I am not sure what this error is implying.
> > ![image](https://user-images.githubusercontent.com/90767085/241845490-33153460-6d2c-467a-b750-37c7a8a4e864.png)

If it does not effect the unlocking process, you can just ignore it

**Closed by 34736384** 2023-05-30 07:18 UTC

**Comment by Arcanologue** [comment] 2023-05-31 20:23
> Try the latest release

@34736384 This is working like a Charm 🙏 thx
